In [15]:
import numpy as np

# 设置随机数生成器的种子
np.random.seed(42)

# 生成随机数
random_numbers = np.random.rand(5)
print(random_numbers)
random_numbers = np.random.rand(5)
print(random_numbers)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]


In [ ]:
from numpy.random import Generator, PCG64

# 创建一个随机数生成器对象
rg = Generator(PCG64(42))

# 生成随机数
random_numbers = rg.random(5)
print(random_numbers)
random_numbers = rg.random(5)
print(random_numbers)
random_numbers = rg.random(5)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
